import Head from "next/head";
import Image from "next/image";
import { MagnifyingGlass, MapPin } from "phosphor-react";

import { InputRoot, InputField } from "../components/Input";
import { BlockCard } from "@/components/BlockCard";

import illustration01 from "../assets/images/ilustra-01.png";
import illustration02 from "../assets/images/ilustra-02.png";

import blocksData from "../database/blocks.json";

export default function Home() {
  return (
    <>
      <Head>
        <title>Find Your Block</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <header className="bg-gray-50 relative py-[200px] md:py-[100px]">
          <div className="max-w-[993px] mx-auto flex flex-col gap-10 items-center px-5">
            <div className="flex flex-col gap-4 items-center z-10">
              <h3 className="text-red-500 font-medium tracking-widest">
                FIND YOUR BLOCK
              </h3>
              <h1 className="text-5xl font-bold text-center">
                Encontre os{" "}
                <span className="text-indigo-500">melhores blocos</span>
                <br />
                de carnaval de 2023
              </h1>
            </div>

            <form className="flex flex-col md:flex-row gap-6 bg-[#FFFFFFBB] p-10 border border-gray-200 rounded-[10px] w-full z-10">
              <InputRoot>
                <MagnifyingGlass className="text-red-500 text-2xl" />
                <InputField placeholder="Pesquise por nome" />
              </InputRoot>

              <InputRoot>
                <MapPin className="text-red-500 text-2xl" />
                <InputField placeholder="Pesquise por cidade" />
              </InputRoot>

              <button className="rounded-[5px] bg-indigo-500 px-8 py-3 text-sm text-white font-bold uppercase">
                Buscar agora
              </button>
            </form>

            <Image
              src={illustration01}
              alt="Ilustração de Carnaval"
              className="absolute left-0 top-0 w-[400px] z-0"
            />

            <Image
              src={illustration02}
              alt="Ilustração de Carnaval"
              className="absolute right-0 bottom-0 w-[400px] z-0"
            />
          </div>
        </header>

        <div className="flex flex-col gap-10 max-w-[1140px] mx-auto my-[100px] px-5">
          <div className="flex justify-between">
            <h2 className="text-3xl font-bold">Blocos recomendados</h2>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {blocksData.map((block) => (
              <BlockCard key={block.id} data={block} />
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
